#!/usr/bin/env bash
set -euo pipefail

# Fix USB serial permissions for ESP32/CDC devices.
# - Temporary fix: chmod on the selected tty device
# - Permanent fix: install udev rule for the USB VID/PID behind that tty
#
# Works both on bare-metal Linux and inside Distrobox/Toolbox containers.
# When a container is detected, privileged operations are delegated to the
# host via distrobox-host-exec.
#
# Usage:
#   ./scripts/fix_usb_serial.sh
#   ./scripts/fix_usb_serial.sh --port /dev/ttyACM0
#   ./scripts/fix_usb_serial.sh --temporary
#
# Defaults:
#   PORT env var -> ./.env PORT=... -> /dev/ttyACM0

PORT_ARG=""
TEMP_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)
      PORT_ARG="${2:-}"
      shift 2
      ;;
    --temporary)
      TEMP_ONLY=1
      shift
      ;;
    -h|--help)
      sed -n '1,28p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

resolve_port() {
  if [[ -n "$PORT_ARG" ]]; then
    echo "$PORT_ARG"
    return
  fi

  if [[ -n "${PORT:-}" ]]; then
    echo "$PORT"
    return
  fi

  if [[ -f .env ]]; then
    local p
    p="$(grep -E '^PORT=' .env | head -n1 | cut -d'=' -f2- | tr -d '"' | xargs || true)"
    if [[ -n "$p" ]]; then
      echo "$p"
      return
    fi
  fi

  echo "/dev/ttyACM0"
}

# Detect Distrobox / rootless-Podman container and choose the right executor.
# Inside a container, sudo has no real host capabilities; use distrobox-host-exec.
in_container() {
  [[ -f /run/.containerenv || -f /.dockerenv ]] || \
    grep -qE '(docker|podman|lxc)' /proc/1/cgroup 2>/dev/null
}

if in_container && command -v distrobox-host-exec &>/dev/null; then
  echo "Container detected – routing privileged calls through distrobox-host-exec."
  SUDO_EXEC="distrobox-host-exec sudo"
else
  SUDO_EXEC="sudo"
fi

PORT_PATH="$(resolve_port)"
TTY_NAME="$(basename "$PORT_PATH")"

if [[ ! -e "$PORT_PATH" ]]; then
  echo "Device not found: $PORT_PATH" >&2
  echo "Tip: reconnect the board and run: ls /dev/ttyACM* /dev/ttyUSB* 2>/dev/null" >&2
  exit 1
fi

if [[ "$PORT_PATH" != /dev/ttyACM* && "$PORT_PATH" != /dev/ttyUSB* ]]; then
  echo "Warning: $PORT_PATH does not look like ttyACM/ttyUSB; continuing anyway."
fi

echo "Using serial device: $PORT_PATH"

# Temporary immediate access fix
$SUDO_EXEC chmod 666 "$PORT_PATH"
echo "Temporary permission set: chmod 666 $PORT_PATH"

if [[ "$TEMP_ONLY" -eq 1 ]]; then
  echo "Done (temporary only)."
  exit 0
fi

# Locate USB parent with idVendor/idProduct in sysfs
SYS_TTY="/sys/class/tty/$TTY_NAME/device"
if [[ ! -e "$SYS_TTY" ]]; then
  echo "Cannot inspect sysfs for $TTY_NAME (path not found: $SYS_TTY)." >&2
  echo "Temporary fix applied; permanent rule skipped." >&2
  exit 0
fi

USB_NODE="$(readlink -f "$SYS_TTY")"
FOUND=0
VID=""
PID=""

for _ in {1..8}; do
  if [[ -f "$USB_NODE/idVendor" && -f "$USB_NODE/idProduct" ]]; then
    VID="$(tr '[:upper:]' '[:lower:]' < "$USB_NODE/idVendor")"
    PID="$(tr '[:upper:]' '[:lower:]' < "$USB_NODE/idProduct")"
    FOUND=1
    break
  fi
  USB_NODE="$(dirname "$USB_NODE")"
done

if [[ "$FOUND" -ne 1 ]]; then
  echo "Could not detect USB VID/PID for $PORT_PATH." >&2
  echo "Temporary fix applied; permanent rule skipped." >&2
  exit 0
fi

RULE_FILE="/etc/udev/rules.d/99-esp32-serial.rules"
RULE_LINE="SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$VID\", ATTRS{idProduct}==\"$PID\", MODE=\"0666\""

echo "Installing udev rule for VID:PID = $VID:$PID"

$SUDO_EXEC bash -c "printf '# Auto-generated by fix_usb_serial.sh\n%s\n' '$RULE_LINE' > '$RULE_FILE'"

$SUDO_EXEC udevadm control --reload-rules || true
$SUDO_EXEC udevadm trigger || true

echo "Permanent rule installed: $RULE_FILE"
echo "Now unplug/replug the board, then verify: ls -l $PORT_PATH"
echo "If group still looks wrong, reboot once."
